services:
    app: # frontend
        build: .
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - .:/app
            - /app/node_modules
            - ./server:/app/server
            - /app/server/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
