services:
    app:
        build: .
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src
                - action: sync
                  path: ./server
                  target: /app/server
        ports:
            - "3000:3000"
            - "5000:5000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
